Description: This is sample cloud formation template to investigate behavior of stack policy.
Resources:
  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-1bfdb67c
      InstanceType: t2.micro
      SecurityGroups:
        - default
      KeyName: default
  SuseInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-e21c7285
      InstanceType: t2.micro
      SecurityGroups:
        - default
      KeyName: default
